# Generated by Django 3.2.5 on 2022-03-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Titulo')),
                ('subtitle', models.CharField(max_length=60, verbose_name='Subtitulo')),
                ('releaseDate', models.DateField()),
                ('director', models.CharField(max_length=60, verbose_name='Director')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='user')),
            ],
        ),
    ]
